// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updatenumberavailabletoexistingmovierecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatenumberavailabletoexistingmovierecords));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041407005_Update number available to existing movie records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
