// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NumberavailableaddedtoMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberavailableaddedtoMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041333281_Number available added to Movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
